name: Copilot Setup Steps

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.15.0
          run_install: true
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Cache node_modules (monorepo)
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Typecheck
        run: pnpm typecheck || true # allow initial scaffolding to proceed

      - name: Tests
        run: pnpm test -- --run || true

      - name: Build
        run: pnpm build || true
